// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Repositories;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250727175257_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Gyümölcsleves tejszínhabbal",
                            Price = 990
                        });
                });

            modelBuilder.Entity("WebApi.Models.MenuItemCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MenuItemCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Levesek"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Meleg előétel"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Húsételek"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hal ételek"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Tészták"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Köretek"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Gyermek menük"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Saláták"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Pizzák"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Tejfölös pizzák"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Specialitások"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Kímélő ételek"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Saláta öntetek"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Desszertek"
                        });
                });

            modelBuilder.Entity("WebApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
